name: Lint Commit Messages

on:
  push:
    branches-ignore:
      - '**'  # 모든 브랜치 무시 (사실상 비활성화)
    #branches:
    #  - master
    #  - "hotfix/*"
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wagoid/commitlint-github-action@v6
